# On Linux:

# Fedora, `sudo dnf install mold clang`
# - Ubuntu, `sudo apt-get install mold clang`
# - Arch, `sudo pacman -S mold clang`
[target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
